P3AddNewFunctionalityDotNetCore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models;

namespace P3AddNewFunctionalityDotNetCore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(ICart cart)
        {
            _cart = cart as Cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

P3AddNewFunctionalityDotNetCore/Components/LanguageSelectorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models.Services;

namespace P3AddNewFunctionalityDotNetCore.Components
{
    public class LanguageSelectorViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ILanguageService languageService)
        {
            return View(languageService);
        }
    }
}

P3AddNewFunctionalityDotNetCore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using P3AddNewFunctionalityDotNetCore.Models.Services;
using P3AddNewFunctionalityDotNetCore.Models.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace P3AddNewFunctionalityDotNetCore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ILanguageService _languageService;

        public ProductController(IProductService productService, ILanguageService languageService)
        {
            _productService = productService;
            _languageService = languageService;
        }

        public IActionResult Index()
        {
            IEnumerable<ProductViewModel> products = _productService.GetAllProductsViewModel();
            return View(products);
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View(_productService.GetAllProductsViewModel().OrderByDescending(p => p.Id));
        }

        [Authorize]
        public ViewResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(ProductViewModel product)
        {
            List<string> modelErrors = new List<string>();
            // TODO validation controls
            // Implement a method inside the ProductService class that will return an error message for each
            // product property that is not conform to its business rules. The return type of the method 
            // must be of List<string>.

            foreach (string error in modelErrors)
            {
                ModelState.AddModelError("", error);
            }

            if (ModelState.IsValid)
            {
                _productService.SaveProduct(product);
                return RedirectToAction("Admin");
            }
            else
            {
                return View(product);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeleteProduct(int id)
        {
            _productService.DeleteProduct(id);
            return RedirectToAction("Admin");
        }
    }
}

P3AddNewFunctionalityDotNetCore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <title>@ViewBag.Title</title>
    @*<script src="/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</head>
<body class="m-1 p-1">
    <div class="bg-warning p-2 row">
        <div class="col" style="padding-left:12%">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">@Localizer["Logout"]</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-8"><p style="padding-top:17px">&copy; 2018 - P3AddNewFunctionalityDotNetCore</p></div>
                <div class="col-4">
                    @await Component.InvokeAsync("LanguageSelector")
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

P3AddNewFunctionalityDotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    @*<link rel="stylesheet" asp-href-include="/css/*.css" />*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <title>@ViewData["Title"] - P3AddNewFunctionalityDotNetCore</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-primary" role="navigation">
        <div class="row">
            <a class="btn btn-warning" asp-action="Admin" asp-controller="Product" style="margin-left:1%; color:black">
                @Localizer["Administrator"]
            </a>
            <a class="col navbar-brand" asp-action="Index" asp-controller="Product" style="padding-left:3%">
                OpenClassrooms shop
            </a>
            <div class="col-4 text-right" style="padding-right:12%">
                @await Component.InvokeAsync("CartSummary")
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-8"><p style="padding-top:17px">&copy; 2018 - P3AddNewFunctionalityDotNetCore</p></div>
                <div class="col-4">
                    @await Component.InvokeAsync("LanguageSelector")
                </div>
            </div>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>